#BUTTON colors
GENERATOR_BUTTON_BCKGRD     = '#00FFC0'
INITIAL_GEN_BUTTON_COLOR    = '#00FF00'
EDIT_PUBLIC_BUTTON_TEXT     = '#FF7F7F'
EDIT_PUBLIC_BUTTON_BCKGRD   = '#EE3333'
RESET_PUBLIC_BUTTON_TEXT    = '#22FF22'
TOGGLE_BUTTON_COLOR_BCKGRD  = '#32CD32'         #for now - the best green variant for buttons!!
MAIN_BACKGROUND             = '#191919'         #neat dark grey
REGULAR_BUTTON_BCKGRD       = '#32CD32'
MESSAGE_INFO_TEXT           = '#32CD32'
MESSAGE_KEY_LENGTH_TEXT     = '#d6d642'
DIMMED_GREEN_COLOUR         = '#74bc5f'
OUTLINE_COLOR_TUPLE         = (0.25, 0.25, 0.25)
OUTLINE_WIDTH               = 2

# #00FFCE