WindowManager:
    MainWindow:
    RSAkeyChange:

<MainWindow>
    name: "main"

    GridLayout:
        cols = 1

        GridLayout:
            cols = 2

            Label:
                text: 'GENERUJ RSA'
                font_size: 18
                color: '#00FFCE'

            Label:
                text: "KLUCZE"
                font_size: 18
                color: '#00FFCE'

        Label:
            text: 'SCHEMAT'

<RSAkeyChange>
    name: "input_key"